### ISSUE TITLE
TODO: Project Review issues

### ISSUE THREAD

**Issue by jack007lyz** [jack007lyz/easy-drive#96]
- [ ] Bottom bar navigate
- [ ] Filter
- [ ] Profile card refactor
- [ ] Favorite
- [ ] Message
- [ ] Calculate rating
- [ ] Following
- [ ] Profile page refactor to MUI
